path:
    # wjd_dump_path : "./data/wikidata/wikidata-20210517-all.json.bz2"
    # db_all_new_names : './data/all_new_names.db'
    # db_all_new_occs : './data/all_new_occs.db'
    # db_all_new_places: './data/all_new_places.db'
    # db_all_new_labels : './data/all_new_labels.db'

    # db_extra : './data/dump/extra.db'
    # db_json : './data/dump/extra.json'

    # db_places : './data/dump/places.db'
    # json_places : './data/dump/places.json'

    # tsv_streets : './data/osm/streets_bremen.tsv'
    # tsv_polygons : ./data/osm/'polygons_bremen.tsv'
    # tsv_test : './data/osm/test.tsv'

    # json_suffix : './data/affixes/suffixe.json'
    # json_prefix : './data/affixes/prefixe.json'
    # titles_json : './data/affixes/suffixe_titel.json'
    # tsv_links : './data/link_counts_wikidata.tsv'
    # db_new_index_person : './data/affixes/new_index.db'

    # csv_named_bremen : './data/affixes/named_bremen.csv'

    # # Person database
    # db_name_data : './data/wikidata/name_data.db'
    # db_new_index : './data/wikidata/new_index.db'

    # # Wikidata ground truth
    # json_gt : './data/wikidata/wikidata_all.json' 

    # json_all_affixes : './data/wikidata/all_affixe.json'

    # wjd_dump_path : "./out/wikidata-20210517-all.json.bz2"


    ##############################################

    tmp : "./out/tmp"
    wjd_dump_path : '/Users/alexis/Documents/04_Code/Y25_streetnameLinks/data/wikidata-20250120-all.json.bz2' # 250127
    db_all_new_names : './out/all_new_names.db'
    db_all_new_occs : './out/all_new_occs.db'
    db_all_new_places: './out/all_new_places.db'
    db_all_new_labels : './out/all_new_labels.db'

    # db_extra : './out/extra.db'
    # db_json : './out/extra.json'
    db_extra : './out/places02.db'
    json_extra : './out/places02.json'


    db_places : './out/places.db'
    json_places : './out/places.json'

    tsv_streets : './data/osm/streets_bremen.tsv'
    tsv_polygons : ./data/osm/'polygons_bremen.tsv'
    tsv_test : './out/test.tsv'

    # json_suffix : './data/affixes/suffixe.json'
    # json_prefix : './data/affixes/prefixe.json'
    json_suffix : './out/suffix.json'
    json_prefix : './out/prefix.json'
    titles_json : './data/affixes/suffixe_titel.json'
    tsv_links : './out/link_counts_wikidata_search2.tsv' #TODO
    tsv_links_test : './out/link_counts_wikidata_test.tsv' #TODO
    db_new_index_person : './out/new_index.db'

    csv_named_location : './out/named_bremen.csv'

    # Person database
    #TODO: CHANGE
    db_name_data : './out/name_data.db'
    # db_name_data : './out/name_data_old.db'
    db_new_index : './out/new_index.db'

    # Wikidata ground truth
    json_gt : './out/wikidata_all.json' 

    json_all_affixes : './out/all_affixe.json'

    filtered_subprops : './data/wikidata/filtered_subprops.json'

    street_candidates : './out/street_candidates.csv'


    street_2_person : './out/wikidata_all.json'

    gt_X_train : './out/gt_X_train.csv'
    gt_y_train : './out/gt_y_train.csv'

    gt_X_test : './out/gt_X_test.csv'
    gt_y_test : './out/gt_y_test.csv'

    ml : './out/rfc_1300.joblib'

    data_ml : './out/ml_gt_data.csv'

search:
    #TODO: change
    lang: 'en'
    # lang : 'de'
    # For area of reference in diustruict_bremen.py
    id_wikidata_ref_test : 'Q24879'
    # choice_country_wikidata : "Q183"    # Germany
    choice_country_wikidata : "Q408"    # Australia

train:
    test_size : .1

predict:
    max_cand : 50